export const mockCategories = [
  {
    id: 1,
    name: "Technology",
    createdAt: "2023-01-15",
    updatedAt: "2023-03-20",
  },
  { id: 2, name: "Health", createdAt: "2023-02-10", updatedAt: "2023-04-05" },
  { id: 3, name: "Business", createdAt: "2023-03-22", updatedAt: "2023-03-22" },
  {
    id: 4,
    name: "Education",
    createdAt: "2023-04-18",
    updatedAt: "2023-05-10",
  },
  {
    id: 5,
    name: "Entertainment",
    createdAt: "2023-05-30",
    updatedAt: "2023-06-15",
  },
];

export const mockContent = [
  {
    id: 1,
    slug: "future-of-ai",
    author_id: 1,
    title: "The Future of AI in Healthcare",
    subtitle: "How artificial intelligence is transforming medical care",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "Technology",
    createdAt: "2023-01-15",
  },
  {
    id: 2,
    slug: "productivity-tips",
    author_id: 2,
    title: "10 Tips for Better Productivity",
    subtitle: "Maximize your efficiency with these proven strategies",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "Business",
    createdAt: "2023-02-10",
  },
  {
    id: 3,
    slug: "blockchain-explained",
    author_id: 1,
    title: "Understanding Blockchain Technology",
    subtitle: "A beginner's guide to blockchain and its applications",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "Technology",
    createdAt: "2023-03-22",
  },
  {
    id: 4,
    slug: "remote-work-guide",
    author_id: 3,
    title: "Guide to Remote Work",
    subtitle: "How to stay productive while working from home",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "Business",
    createdAt: "2023-04-18",
  },
  {
    id: 5,
    slug: "web-dev-trends",
    author_id: 2,
    title: "Latest Trends in Web Development",
    subtitle: "Stay updated with the newest technologies and frameworks",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    category: "Technology",
    createdAt: "2023-05-30",
  },
];
